[package]
name = "pacosako-rust"
version = "0.1.0"
authors = ["rolf"]
edition = "2018"

[dependencies]
colored = "1.8.0"
rand = "0.6.5"
nom = "5.0.0-beta2"

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"