[package]
name = "pacosako-rust"
version = "0.1.0"
authors = ["rolf"]
edition = "2018"

[dependencies]
colored = "1.8.0"
rand = "0.7.0"
nom = "5.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"